### ISSUE TITLE
Can't see metric on the left

### ISSUE THREAD

**Issue by sglwlb** [Ticketmaster/metrilyx-2.0#85] opened 2015-04-09 15:39 UTC
After setup the metrilyx, i could access the web, but no metrics are there.
Setup steps are:
1. install nginx and mv /etc/nginx/conf.d/default.conf{,.disabled}
2. install metrilyx
3. vim /opt/metrilyx/etc/metrilyx/metrilyx.conf
      "dataprovider": {
                "name": "OpenTSDB",
                "uri": "http://192.168.2.107",
                "port": 4242,
                "suggest_limit": 50, 
                "query_endpoint": "/api/query",
                "search_endpoint": "/api/suggest",
                "loader_class": "opentsdb.OpenTSDBDataProvider"
        },

4. /etc/init.d/metrilyx start & /etc/init.d/nginx start

After installation, i access the webpage, there are only Overview and TSD(I think they are default), i can't see other metrics i have into the opentsdb, for example, i could query:
./tsdb query 24h-ago sum ost_kbytesinfo_total
ost_kbytesinfo_total 1428576240000 20635372.000000 {fs_name=vm05, fqdn=vm05}

When i try to search ost_kbytesinfo_total, here is message from js console:

finished loading: GET "http://192.168.2.107/search/metrics?q=ost_kbytesinfo_total".
finished loading: GET "http://192.168.2.107/api/schemas/metric".

seems every thing is ok.And the log is like:
tail metrilyx-cacher.log
2015/04/09 23:31:42 Running cache collection...
2015/04/09 23:31:42 Cache collection complete!
2015/04/09 23:33:14 GET 200 /metrics?q=ost_kbytesinfo_total 127.0.0.1:53589
2015/04/09 23:34:42 Running cache collection...
2015/04/09 23:34:42 Cache collection complete!

But i could not see any request from metrilyx to opentsdb to query the ost_kbytesinfo_total metric.

Any idea of my problem? Am I missing some configuration?

Platform:
CentOS 6.5
metrilyx: metrilyx-2.0-2.5.1-17.el6.x86_64
nginx: nginx-release-centos-6-0.el6.ngx.noarch
           nginx-1.6.3-1.el6.ngx.x86_64

**Comment by euforia** [comment] 2015-04-09 16:53
is the cacher actually enabled in the config? If the cacher is not enabled it will go directly to tsdb on the /api/suggest endpoint.

**Comment by sglwlb** [comment] 2015-04-10 05:44
Thanks, @euforia . It's the cache problem, now it's OK.
Now i could create a new page and drag metrics into it, and save the page, but i can't see any graph on it. It's blank, i click refresh, and i could see the query request at opentsdb side, but no graph show on the page. Btw, it has that metric in opentsdb, i could query it.

**Comment by euforia** [comment] 2015-04-13 18:41
can you send me the output of the javascript console from chrome?  that should give me a better idea.

**Comment by evnaresh** [comment] 2015-04-14 08:57
I seem to have a similar situation where the metrics are not visible in the left pane of the portal application.
Following is the metrilyx cacher configuration (metrilyx.conf):

 "cache": {
                "enabled": true,
                "interval": 180,
        "result_size": 150,
        "datasource": {
                "url": "/search"
        }
        },

metrilyx-cacher.log output:
parse :0?max=16000000&q=0&type=tagv: missing protocol scheme
parse :0?max=16000000&q=1&type=tagv: missing protocol scheme
parse :0?max=16000000&q=2&type=tagv: missing protocol scheme
parse :0?max=16000000&q=3&type=tagv: missing protocol scheme
parse :0?max=16000000&q=4&type=tagv: missing protocol scheme
parse :0?max=16000000&q=5&type=tagv: missing protocol scheme
parse :0?max=16000000&q=6&type=tagv: missing protocol scheme
parse :0?max=16000000&q=7&type=tagv: missing protocol scheme
parse :0?max=16000000&q=8&type=tagv: missing protocol scheme
parse :0?max=16000000&q=9&type=tagv: missing protocol scheme
2015/04/14 08:53:42 Cache collection complete!
2015/04/14 08:54:06 GET 200 /metrics?q=prd. 127.0.0.1:57765

Version of metrilyx: metrilyx-2.0_2.5.1-18_amd64.deb

**Comment by clohtd** [comment] 2015-04-14 14:19
The missing protocol scheme error seems to be an opportunity for improvement.  The current workaround is to modify the /etc/init.d/metrilynx-cacher file and replace

DEFAULT_OPTS="-config $CACHER_CONFIG";
with
DEFAULT_OPTS="-url http://tsdbservername:4242/api/suggest";

**Comment by euforia** [comment] 2015-04-14 17:04
This is a bug.  I'm working as we speak.  I'll keep you posted.

**Comment by euforia** [comment] 2015-04-14 17:18
Seems like there's a syntax error in the json config file.  If you remove the comma after the ssl field under the websocket section, that should fix the problem.  Please let me know.

**Comment by clohtd** [comment] 2015-04-14 18:21
Confirmed that it works.

**Comment by euforia** [comment] 2015-04-14 18:27
Packages for 2.5.1 have been updated with this fix.  Closing this out.  Feel free to open if the problem still persists.

**Closed by euforia** 2015-04-14 18:27 UTC
Labels: bug

**Comment by sglwlb** [comment] 2015-04-19 03:32
Interesting, things change here. Follow is my configuration:
{
        "dataprovider": {
                "name": "OpenTSDB",
                "uri": "http://192.168.2.107",
                "port": 4242,
                "suggest_limit": 50, 
                "query_endpoint": "/api/query",
                "search_endpoint": "/api/suggest",
                "loader_class": "opentsdb.OpenTSDBDataProvider"
        },  
        "databases":[
                {   
                        "ENGINE": "django.db.backends.sqlite3",
                "NAME": "data/metrilyx.sqlite3"
                },{ 
                        "ENGINE": "django.db.backends.postgresql_psycopg2",
                        "NAME": "metrilyx",
                        "HOST": "127.0.0.1",
                        "PORT": "5432",
                        "USER": "metuser",
                        "PASSWORD": "metpass"
                }   
        ],  
        "cache": {
                "enabled": false,
                "interval": 180,
        "result_size": 50, 
        "datasource": {
                "url": "/search"
        }   
        },  
        "annotations": {
                "enabled": false,
                "url": "http://localhost:9898",
                "endpoints": {
                        "annotate": "/api/annotations",
                        "search": "/api/query",
                        "types": "/api/types"
                },  
                "websocket": {
                        "uri": "ws://localhost:9898/annotations/data"
                }   
        },  
        "websocket": {
                "endpoint": "/api/data",
                "ssl": false,
                "server": "192.168.2.107"
        },  
        "tmpdir": "/dev/shm/metrilyx",
        "debug": false,
        "version": "2.5.1"
}

And when i fresh the graph, follow errors:
WebSocket connection to 'ws://server/api/data?compressed=true' failed: Error during WebSocket handshake: Unexpected response code: 404
Disconnected (metrilyx): clean=false, code=1006, reason=''
Connect state: disconnected
Re-connecting...


Sorry to reply late,but what's the problem of mine, thanks.

**Comment by euforia** [comment] 2015-04-20 04:16
In the websocket section, 'server' field should be 'hostname'

**Comment by sglwlb** [comment] 2015-04-20 10:21
Oh, yeah, the 'hostname' of '192.168.2.107' is 'server'.
